import {initializeApp} from 'firebase-admin/app';
import {getFirestore} from 'firebase-admin/firestore';
import {getStorage} from 'firebase-admin/storage';
import {onCall,onRequest,HttpsError} from 'firebase-functions/v2/https';
import {setGlobalOptions} from 'firebase-functions/v2';
import {freshGame,applyAction,requireThat,safeText,checkProof,bossReady,guideLevel} from './game/engine.js';
import {missions,worlds,guides} from './game/content.js';
import {guideReply,assessBoss} from './game/coaching.js';
import {isOwner,cleanAnnouncement} from './game/admin.js';
import {cleanResources,cleanChat} from './game/community.js';
import {createCheckoutSession,verifyBillingEvent} from './adapters/subscription.js';
initializeApp();const db=getFirestore();
setGlobalOptions({region:process.env.FUNCTIONS_REGION||'us-central1',maxInstances:10});
const opts={enforceAppCheck:process.env.ENFORCE_APP_CHECK==='true',timeoutSeconds:60};
const playerRef=uid=>db.doc(`players/${uid}`);
const proofRef=(uid,id)=>db.doc(`players/${uid}/proofs/${id}`);
const idCheck=id=>requireThat(typeof id==='string'&&/^[a-zA-Z0-9_-]{1,128}$/.test(id),'Invalid identifier.');
const signed=r=>{if(!r.auth)throw new HttpsError('unauthenticated','Sign in to continue.');return r.auth.uid;};
const guarded=(fn,extra={})=>onCall({...opts,...extra},async r=>{try{return await fn(r);}catch(e){if(e instanceof HttpsError)throw e;throw new HttpsError('failed-precondition',e.message||'Unable to complete this move.');}});
async function ownerOnly(r){const uid=signed(r);requireThat(r.auth.token.owner===true,'Owner access required.');const cfg=await db.doc('privateConfig/owner').get();requireThat(isOwner(uid,r.auth.token,cfg.data()?.uid),'Owner access required.');return uid;}
async function ensurePlayer(uid){await db.runTransaction(async tx=>{const ref=playerRef(uid),doc=await tx.get(ref);if(!doc.exists)tx.set(ref,{game:freshGame(),revision:0});});}
async function access(tx,uid,world){if(process.env.REQUIRE_MEMBERSHIP!=='true'||world===0)return;const e=await tx.get(db.doc(`entitlements/${uid}`));requireThat(e.exists&&e.data().active===true&&e.data().expiresAt>Date.now(),'An active adventure pass is required for this world. Visit Membership.');}
async function getProofs(uid){return (await playerRef(uid).collection('proofs').orderBy('createdAt','desc').limit(100).get()).docs.map(d=>({id:d.id,...d.data()}));}
export const getPlayer=guarded(async r=>{const uid=signed(r);await ensurePlayer(uid);const [p,proofs,e,resources,owner,announcement]=await Promise.all([playerRef(uid).get(),getProofs(uid),db.doc(`entitlements/${uid}`).get(),db.doc('appConfig/resources').get(),db.doc('privateConfig/owner').get(),db.doc('appConfig/announcement').get()]);return {isOwner:isOwner(uid,r.auth.token,owner.data()?.uid),announcement:announcement.data()||null,game:p.data().game,proofs,resources:resources.exists?resources.data():null,entitlement:!!(e.exists&&e.data().active&&e.data().expiresAt>Date.now())};});
export const gameAction=guarded(async r=>{const uid=signed(r),a=r.data;requireThat(a&&['profile','step'].includes(a.type),'This action is server-only.');await ensurePlayer(uid);return db.runTransaction(async tx=>{const ref=playerRef(uid),doc=await tx.get(ref);const m=missions.find(x=>x.id===a.missionId);if(a.type==='step'){requireThat(m,'Unknown mission.');await access(tx,uid,m.world);}const game=applyAction(doc.data().game,a);tx.update(ref,{game,revision:doc.data().revision+1});return {ok:true};});});
export const submitProof=guarded(async r=>{const uid=signed(r),{missionId,proofId,proof,attachment}=r.data;idCheck(proofId);const m=missions.find(x=>x.id===missionId);requireThat(m,'Unknown mission.');checkProof(proof,m);let cleanAttachment=null;
 if(attachment){const path=`proofs/${uid}/${proofId}/evidence`;requireThat(attachment.path===path,'Invalid evidence path.');const [meta]=await getStorage().bucket().file(path).getMetadata();requireThat(Number(meta.size)<=5*1024*1024&&['image/jpeg','image/png','image/webp','application/pdf'].includes(meta.contentType),'Invalid evidence file.');cleanAttachment={path,name:safeText(attachment.name,1,200),size:Number(meta.size),type:meta.contentType};}
 return db.runTransaction(async tx=>{const ref=playerRef(uid),pRef=proofRef(uid,proofId);const [doc,old]=await Promise.all([tx.get(ref),tx.get(pRef)]);requireThat(doc.exists,'Start your player profile first.');await access(tx,uid,m.world);if(old.exists)return {ok:true};const game=applyAction(doc.data().game,{type:'submit',missionId,proofId,proof});tx.create(pRef,{uid,missionId,summary:proof.summary.trim(),evidence:proof.evidence.map(x=>x.trim()),url:proof.url||'',attachment:cleanAttachment,status:'pending',createdAt:Date.now(),feedback:''});tx.update(ref,{game,revision:doc.data().revision+1});return {ok:true};});});
export const reviewQueue=guarded(async r=>{const uid=signed(r);await ownerOnly(r);const q=await db.collectionGroup('proofs').where('status','==','pending').limit(100).get();return q.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.uid!==uid);});
export const reviewProof=guarded(async r=>{const reviewer=signed(r);const {uid,proofId,approved,feedback}=r.data;idCheck(uid);idCheck(proofId);requireThat(uid!==reviewer,'Reviewers cannot approve their own evidence.');await ownerOnly(r);safeText(feedback,10,2000);requireThat(typeof approved==='boolean','Select a review decision.');return db.runTransaction(async tx=>{const ref=playerRef(uid),pRef=proofRef(uid,proofId);const [doc,p]=await Promise.all([tx.get(ref),tx.get(pRef)]);requireThat(doc.exists&&p.exists,'Proof not found.');requireThat(p.data().status==='pending','This evidence has already been reviewed.');const game=applyAction(doc.data().game,{type:'review',missionId:p.data().missionId,proofId,approved,feedback});tx.update(ref,{game,revision:doc.data().revision+1});tx.update(pRef,{status:approved?'verified':'rejected',feedback,reviewer,reviewedAt:Date.now()});return {ok:true};});});
export const askGuide=guarded(async r=>{const uid=signed(r),{guideId,message,reset=false}=r.data;requireThat(guides.some(g=>g.id===guideId),'Unknown Guide.');safeText(message,3,2000);requireThat(typeof reset==='boolean','Invalid reset option.');await ensurePlayer(uid);return db.runTransaction(async tx=>{const ref=playerRef(uid),doc=await tx.get(ref),game=doc.data().game;const reply=guideReply({game,guideId,message,reset});const history=game.chats[guideId]||[];history.push({role:'user',text:message},{role:'guide',text:reply.text});game.chats[guideId]=history.slice(-12);game.coaching=game.coaching||{};game.coaching[guideId]={...reply.memory,question:reply.question};game.updatedAt=Date.now();tx.update(ref,{game,revision:doc.data().revision+1});return {text:reply.text,question:reply.question,mode:reply.mode};});});
export const battle=guarded(async r=>{const uid=signed(r),{worldId,answer,expectedRound,choice,check,scenarioId}=r.data;const w=worlds.find(x=>x.id===worldId);requireThat(w,'Unknown world.');safeText(answer,40,3000);return db.runTransaction(async tx=>{const ref=playerRef(uid),doc=await tx.get(ref);requireThat(doc.exists&&bossReady(doc.data().game,w.index),'Verify both world missions first.');const game=doc.data().game;requireThat((game.bosses[w.id]?.round||0)===expectedRound&&!game.bosses[w.id]?.won,'Battle has changed. Refresh and try again.');await access(tx,uid,w.index);const reply=assessBoss({game,world:w,answer,choice,check,scenarioId});const next=applyAction(game,{type:'boss',worldId,answer,expectedRound,passed:reply.passed,feedback:reply.feedback});const record=next.bosses[worldId].history.at(-1);Object.assign(record,{choice,check,scenarioId,assessment:'built-in strategy rubric'});tx.update(ref,{game:next,revision:doc.data().revision+1});return reply;});});
export const createCheckout=guarded(async r=>{const uid=signed(r);const result=await createCheckoutSession({uid,email:r.auth.token.email||null});requireThat(new URL(result.url).protocol==='https:','Invalid checkout URL.');return result;});
export const billingWebhook=onRequest({timeoutSeconds:30},async(req,res)=>{if(req.method!=='POST'){res.status(405).send('POST required');return;}try{const event=await verifyBillingEvent(req.rawBody,req.headers);idCheck(event.id);idCheck(event.uid);requireThat(typeof event.active==='boolean'&&Number.isFinite(event.expiresAt)&&Number.isFinite(event.occurredAt),'Invalid billing event.');await db.runTransaction(async tx=>{const eventRef=db.doc(`billingEvents/${event.id}`),entRef=db.doc(`entitlements/${event.uid}`);const [seen,ent]=await Promise.all([tx.get(eventRef),tx.get(entRef)]);if(seen.exists)return;tx.create(eventRef,{uid:event.uid,receivedAt:Date.now()});if(!ent.exists||event.occurredAt>(ent.data().occurredAt||0))tx.set(entRef,{active:event.active,expiresAt:event.expiresAt,occurredAt:event.occurredAt});});res.status(200).send('OK');}catch{res.status(400).send('Billing event not accepted');}});

// Gamer chat: authenticated members share a single real-time lobby.
export const saveResources=guarded(async r=>{const uid=signed(r);await ownerOnly(r);const clean=cleanResources(r.data?.resources),expectedRevision=r.data?.expectedRevision;return db.runTransaction(async tx=>{const ref=db.doc('appConfig/resources'),old=await tx.get(ref);const revision=old.data()?.revision||0;requireThat(expectedRevision===revision,'Resources changed elsewhere. Refresh before editing.');tx.set(ref,{...clean,revision:revision+1,updatedAt:Date.now(),updatedBy:uid});return {ok:true};});});

export const getAdminOverview=guarded(async r=>{await ownerOnly(r);const [players,proofs,resources,announcement]=await Promise.all([db.collection('players').count().get(),db.collectionGroup('proofs').where('status','==','pending').count().get(),db.doc('appConfig/resources').get(),db.doc('appConfig/announcement').get()]);return {playerCount:players.data().count,pendingProofs:proofs.data().count,resources:resources.data()||null,announcement:announcement.data()||{title:'',body:'',enabled:false}};});
export const saveAnnouncement=guarded(async r=>{const uid=await ownerOnly(r),announcement=cleanAnnouncement(r.data);await db.doc('appConfig/announcement').set({...announcement,updatedBy:uid,updatedAt:Date.now()});return {ok:true};});

export const sendChat=guarded(async r=>{const uid=signed(r),text=cleanChat(r.data?.text),messageId=r.data?.messageId;idCheck(messageId);return db.runTransaction(async tx=>{const pRef=playerRef(uid),qRef=db.doc(`chatQuotas/${uid}`),mRef=db.doc(`gamerChat/${messageId}`);const [p,q,m,mute]=await Promise.all([tx.get(pRef),tx.get(qRef),tx.get(mRef),tx.get(db.doc(`chatMutes/${uid}`))]);requireThat(p.exists,'Create your character first.');requireThat(!mute.exists||mute.data().until<=Date.now(),'Chat is temporarily muted for this account.');if(m.exists){requireThat(m.data().uid===uid,'Invalid message ID.');return {ok:true};}const now=Date.now(),previous=q.data()||{},same=now-(previous.window||0)<60000;requireThat(!same||(previous.count||0)<10,'Please wait before sending more messages.');tx.set(qRef,{window:same?previous.window:now,count:same?previous.count+1:1});tx.create(mRef,{uid,playerName:p.data().game.profile.name,avatar:p.data().game.profile.avatar,text,createdAt:now,removed:false});return {ok:true};});});
export const reportChat=guarded(async r=>{const uid=signed(r),{messageId,reason}=r.data;idCheck(messageId);safeText(reason,3,500);const m=await db.doc(`gamerChat/${messageId}`).get();requireThat(m.exists,'Message not found.');await db.doc(`chatReports/${messageId}_${uid}`).set({messageId,reportedBy:uid,reason,createdAt:Date.now(),status:'open'});return {ok:true};});
export const moderateChat=guarded(async r=>{const actor=await ownerOnly(r);const {messageId,mute}=r.data;idCheck(messageId);return db.runTransaction(async tx=>{const ref=db.doc(`gamerChat/${messageId}`),m=await tx.get(ref);requireThat(m.exists,'Message not found.');tx.update(ref,{text:'Message removed by the owner.',removed:true,moderatedBy:actor});if(mute===true)tx.set(db.doc(`chatMutes/${m.data().uid}`),{until:Date.now()+86400000,moderatedBy:actor});return {ok:true};});});
export const getChatReports=guarded(async r=>{await ownerOnly(r);const q=await db.collection('chatReports').where('status','==','open').limit(50).get();return Promise.all(q.docs.map(async d=>{const data=d.data(),m=await db.doc(`gamerChat/${data.messageId}`).get();return {id:d.id,...data,messageText:m.data()?.text||'Message unavailable'};}));});
export const resolveChatReport=guarded(async r=>{const uid=await ownerOnly(r),id=safeText(r.data?.id,1,300);requireThat(!id.includes('/'),'Invalid report ID.');await db.doc(`chatReports/${id}`).update({status:'resolved',resolvedBy:uid});return {ok:true};});
