export const guides = [
 {id:'strategist',name:'Strategist',icon:'Compass',role:'Clarity & direction',skill:'Strategy'},
 {id:'creator',name:'Creator',icon:'Feather',role:'Message & visibility',skill:'Creativity'},
 {id:'builder',name:'Builder',icon:'Hammer',role:'Offers & systems',skill:'Building'},
 {id:'closer',name:'Closer',icon:'Swords',role:'Conversations & sales',skill:'Connection'},
 {id:'analyst',name:'Analyst',icon:'ChartNoAxesCombined',role:'Numbers & experiments',skill:'Analysis'},
 {id:'spark',name:'Spark',icon:'Zap',role:'Confidence & action',skill:'Momentum'}
];
export const worlds = [
 ['foundation','Foundation','Start with clarity','Compass','strategist','The Fog','Strategy'],
 ['brand','Brand & Message','Find your voice','Feather','creator','The Echo','Creativity'],
 ['offer','Offer Creation','Build something useful','Gem','builder','The Price Monster','Building'],
 ['visibility','Visibility','Be seen by the right people','Radio','creator','The Algorithm','Creativity'],
 ['conversations','Conversations','Make real connections','MessagesSquare','closer','The Ghost','Connection'],
 ['sales','Sales Arena','Listen. Understand. Offer.','Swords','closer','The No','Connection'],
 ['experience','Customer Experience','Deliver with care','HeartHandshake','builder','The Expectation Gap','Building'],
 ['growth','Growth & Systems','Make room to grow','Settings','analyst','The Chaos','Analysis'],
 ['freedom','Wealth & Freedom','Create your options','Crown','spark','The Treadmill','Momentum']
].map(([id,name,tagline,icon,guide,boss,skill],index)=>({id,name,tagline,icon,guide,boss,skill,index}));
const lessons = [
 ['Choose your starting point','An audience is a group with a shared problem. Start with a skill you can use and a specific person you can help. Treat your idea as a hypothesis to test, not a promise of success.','Which starting point is easiest to test?',['Everyone who wants a better life','Local dog walkers who need booking help','Anyone who might buy something'],1,'I can help [specific people] with [problem] using [skill]. This week I will test [small action].','Ask one person in your chosen audience about this problem. Record their answer without their name.',['Specific audience','A problem in their own words','A small next experiment']],
 ['Listen before you build','Useful research asks about past behaviour. “Tell me about the last time this happened” gives better evidence than “Would you buy my idea?” Avoid leading questions.','Which question invites useful evidence?',['You love this idea, right?','Would you pay someday?','What happened the last time you faced this?'],2,'Last time this happened: …\nWhat they tried: …\nWhat was difficult: …\nWhat I changed after listening: …','Have a short, consensual research conversation. Save redacted notes and one change you will make.',['Past behaviour recorded','Existing workaround','An insight that changes your plan']],
 ['Write a clear message','A clear message connects a person, a problem, and a useful outcome. Specificity makes it easier for the right person to recognise themselves. Avoid guarantees and exaggerated claims.','Which message is most specific?',['I help everyone win','I organise booking requests for independent dog walkers','Best service ever'],1,'I help [audience] do [useful outcome] through [approach]. Here is a realistic example: …','Share this message with one intended reader. Ask what they think you do and record their response.',['Audience named','Plain-language outcome','Reader feedback']],
 ['Build your business profile','A useful profile says who you help, what you do, and how to take a low-pressure next step. Make your claims accurate and your contact route clear.','What belongs in a useful profile?',['Unverifiable income claims','Only a clever quote','Audience, service, and a clear next step'],2,'Who I help: …\nHow I help: …\nEvidence or relevant experience: …\nNext step: …','Update a real business profile or share your profile draft privately with an intended reader. Submit a redacted screenshot or structured feedback.',['Clear audience','Accurate description','Contact or next step']],
 ['Shape a useful offer','An offer defines a problem, deliverables, boundaries, timing, and price. Start with a scope you can deliver well. A price is a hypothesis, not proof that demand exists.','What reduces confusion?',['Promising unlimited results','Clear deliverables and exclusions','Hiding the price until the end'],1,'Problem: …\nDeliverables: …\nNot included: …\nTimeframe: …\nPrice hypothesis: …','Show your offer draft to one potential customer. Capture their questions and revise one unclear detail.',['Deliverables and scope','Timeframe and price hypothesis','Feedback and revision']],
 ['Test your offer','A small test helps you learn before investing heavily. Ask permission, explain what is available, and record interest honestly. “No” is useful feedback, not failure.','Which is evidence of interest?',['A genuine request for more details','Your own excitement','A made-up testimonial'],0,'Test audience: …\nInvitation: …\nWhat actually happened: …\nNext adjustment: …','Send one respectful offer invitation with an easy way to decline. Record the response, including no response.',['Real invitation','Observed response','One next adjustment']],
 ['Create a useful post','Useful content starts with a real question, gives one practical answer, and ends with an appropriate next step. Attention alone is not proof of business value.','Which post is useful?',['A guaranteed income promise','A vague motivational slogan','One clear answer to a real audience question'],2,'Audience question: …\nOpening: …\nUseful answer: …\nOptional next step: …','Publish your post or share it with an intended reader in an appropriate space. Save its URL or a redacted screenshot and context.',['Clear audience question','Useful answer','Evidence it was shared']],
 ['Run a visibility experiment','Change one thing at a time. Choose a measure before posting and compare what happened with what you expected. Small samples are learning signals, not certainty.','What makes a useful experiment?',['Changing everything at once','One change and a defined measure','Counting only favourable results'],1,'Hypothesis: …\nOne change: …\nMeasure and observation window: …\nObserved result: …','Run a small content experiment and record the actual observation, even if it is zero.',['One variable','Defined measure','Actual observation']],
 ['Start a real conversation','Good outreach is relevant, respectful, and easy to decline. Start with curiosity. Do not add people to lists or pressure them to respond.','Which opener respects the other person?',['Can I ask one question about your booking process? No worries if not.','Why have you ignored me?','Buy now or lose your chance'],0,'Why this person: …\nPermission-based opening: …\nQuestion: …\nWhat they said: …','Have one permission-based conversation. Save a redacted summary; a respectful decline counts as a real outcome.',['Relevant context','Permission requested','Actual response or decline']],
 ['Follow up with care','A follow-up should add relevant context and respect boundaries. If someone declines or asks you to stop, stop. Silence is not permission to repeatedly contact them.','What follows a clear no?',['Use another account','Respect the decision and stop','Send a daily reminder'],1,'Previous context: …\nUseful follow-up: …\nBoundary I will respect: …\nOutcome: …','Make one appropriate follow-up where permission exists, or document why the right decision was not to contact again.',['Prior context','Respectful boundary','Action and outcome']],
 ['Lead a discovery conversation','Discovery is about fit: ask about the problem, current approach, desired change, and constraints. Recommend an offer only if it can reasonably help.','When should you recommend your offer?',['When the person is confused','At any cost','When needs and scope fit'],2,'Their problem: …\nCurrent approach: …\nDesired change: …\nConstraints: …\nFit or not-fit decision: …','Hold a discovery conversation or a disclosed roleplay with a willing partner. Save notes and explain your fit decision.',['Needs recorded','Constraints considered','Honest fit decision']],
 ['Respond to an objection','An objection can be a request for clarity or a sign of poor fit. Ask what the concern means, explain relevant value without guarantees, and leave room for no.','How do you respond to “too expensive”?',['Shame the buyer','Ask about their concern and explore fit','Guarantee they will earn it back'],1,'Concern: …\nClarifying question: …\nRelevant explanation: …\nRespectful next step: …','Practise with a willing partner or respond to a real objection. Record the question, response, and what you learned.',['Concern understood','No pressure or guarantees','Clear next step']],
 ['Design a welcome experience','A clear welcome reduces uncertainty. Set expectations for scope, timing, communication, and the first step. Only collect information you actually need.','What should onboarding clarify?',['Scope, timing, and first step','Every personal detail','Only your company story'],0,'Welcome: …\nWhat happens next: …\nTimeline: …\nCommunication: …\nWhat I need: …','Test your welcome instructions with one willing person and record what was unclear.',['Scope and timeline','Communication route','Tester feedback']],
 ['Close the feedback loop','Feedback helps you improve delivery. Ask what worked, what was difficult, and what would help. Get explicit permission before using a quote publicly.','Before sharing a testimonial, you should…',['Rewrite it to promise results','Publish it without asking','Get permission for the exact use'],2,'What worked: …\nWhat was difficult: …\nImprovement: …\nPermission status: …','Collect feedback on a real or pilot deliverable and implement one improvement.',['Feedback collected','Improvement made','Privacy and permission considered']],
 ['Build a repeatable system','A system is a sequence someone can follow. Start with one repeated task, define the trigger, steps, and finish condition, then test it manually before automating.','What comes before automation?',['Buying every tool','Testing a clear manual process','Skipping exception handling'],1,'Trigger: …\nSteps: …\nDone means: …\nExceptions: …','Use your checklist on one real task. Record where it helped and where it failed.',['Trigger and finish','Repeatable steps','Actual test and revision']],
 ['Read your numbers','Separate activity from outcomes. Track a small set of measures with dates and definitions. Do not treat a tiny sample as proof or confuse revenue with profit.','Revenue minus business expenses is closest to…',['Follower count','Guaranteed future income','Profit before any other applicable costs or taxes'],2,'Period: …\nActivity measure: …\nOutcome measure: …\nCosts or time: …\nDecision: …','Record one period of real observations and choose a small next experiment. Zero is a valid observation.',['Dates and definitions','Actual observations','Evidence-based next experiment']],
 ['Design your options','Options are possible paths you have prepared to explore, not income guarantees. Consider your available time, resources, preferences, and downside before choosing a path.','What is an unlocked option in OYO?',['Guaranteed income','A prepared path to explore','Financial advice'],1,'Path I could explore: …\nExisting skills: …\nTime and resources: …\nRisks and limits: …\nSmall test: …','Discuss your plan with a trusted person or test its time requirements in a real week. Record one adjustment.',['Resources and constraints','Risks considered','Real-world feedback']],
 ['Build a sustainable next chapter','A useful plan protects capacity. Decide what to continue, stop, and test. Revisit the plan with actual evidence; no single business model works for everyone.','Which plan is most sustainable?',['Work all the time','Ignore the evidence','A small experiment with a capacity limit and review date'],2,'Continue: …\nStop: …\nNext experiment: …\nCapacity limit: …\nReview date: …','Schedule and begin one bounded experiment. Submit the first action and your review plan.',['Capacity limit','First action taken','Review date set']]
];
export const missions=lessons.map(([title,lesson,question,answers,correct,template,irl,criteria],i)=>({id:`m${i+1}`,world:Math.floor(i/2),title,lesson,question,answers,correct,template,irl,criteria,xp:150+(Math.floor(i/2)*25)}));
export const steps=['Learn','Practice','Build','Do It IRL','Submit Proof','Verify','Unlock'];
export const optionNames=['Service experiment','Brand collaboration','Pilot offer','Content channel','Referral conversations','Sales process','Repeat delivery','Systemised service','Sustainable portfolio'];
export const bossPrompts=[
 'Your idea is too broad. Name one audience, one real problem, and a small action to test it.',
 'Someone says your message sounds like everyone else. Explain who it is for, what it helps them do, and a concrete example.',
 '“That is too expensive.” Ask a clarifying question, explain scope, and offer a pressure-free next step.',
 'Your last post had little response. Propose one change, one measure, and a fair observation window.',
 'A person stopped responding. Describe a respectful boundary, an appropriate action, and what you will learn.',
 'A prospect says no. Acknowledge their choice, explain how you will respect it, and identify a useful lesson.',
 'A customer expected something outside your scope. Acknowledge the concern, clarify the agreement, and propose a fair next step.',
 'Your repeated process broke. Identify the bottleneck, one process change, and a way to check it.',
 'You have more opportunities than time. Choose what to stop, protect a capacity limit, and set a review date.'
];
