import test from 'node:test';
import assert from 'node:assert/strict';
import {freshGame,applyAction,missionState,worldOpen,missionOpen,bossReady,trainingBoss,guideLevel,checkProof,safeURL} from '../functions/game/engine.js';
import {missions,worlds} from '../functions/game/content.js';
const proof={summary:'I interviewed a willing person about their actual booking process and recorded the challenge they described.',evidence:['I identified a specific audience and the context of their current work.','The participant described a real problem using their own words in my notes.','I selected a small experiment based on the actual feedback I received.'],url:''};
function stage(g,m){for(let i=0;i<4;i++)g=applyAction(g,{type:'step',missionId:m.id,expectedStep:i,answer:m.correct,draft:'My useful business asset explains an audience, a problem, an action and a way to test it with a willing participant.',confirmed:true});return g;}
function complete(g,m){g=stage(g,m);g=applyAction(g,{type:'submit',missionId:m.id,proofId:`proof-${m.id}`,proof});return applyAction(g,{type:'review',missionId:m.id,proofId:`proof-${m.id}`,approved:true,feedback:'The submitted evidence addresses every completion criterion.'});}
test('new players have exactly one available mission and no free XP',()=>{const g=freshGame();assert.equal(g.xp,0);assert.equal(missions.filter(m=>missionOpen(g,m.id)).length,1);assert.equal(worldOpen(g,1),false);});
test('locked mission cannot be advanced',()=>assert.throws(()=>applyAction(freshGame(),{type:'step',missionId:'m3',expectedStep:0}),/locked/));
test('wrong practice answer does not change progress',()=>{const g=applyAction(freshGame(),{type:'step',missionId:'m1',expectedStep:0});assert.throws(()=>applyAction(g,{type:'step',missionId:'m1',expectedStep:1,answer:0}),/Not quite/);assert.equal(g.missions.m1.step,1);});
test('stale or repeated stage does not skip progression',()=>{const g=applyAction(freshGame(),{type:'step',missionId:'m1',expectedStep:0});assert.throws(()=>applyAction(g,{type:'step',missionId:'m1',expectedStep:0}),/changed/);});
test('empty and inadequate proof are rejected',()=>{assert.throws(()=>checkProof({...proof,summary:'done'},missions[0]));assert.throws(()=>checkProof({...proof,evidence:['short']},missions[0]));assert.throws(()=>safeURL('javascript:alert(1)'));});
test('submitted proof grants no XP and does not open next mission',()=>{let g=stage(freshGame(),missions[0]);g=applyAction(g,{type:'submit',missionId:'m1',proofId:'p1',proof});assert.equal(g.xp,0);assert.equal(missionOpen(g,'m2'),false);assert.equal(missionState(g,'m1').status,'pending');});
test('verified proof grants XP once and opens only the next mission',()=>{const g=complete(freshGame(),missions[0]);assert.equal(g.xp,150);assert.equal(missionOpen(g,'m2'),true);assert.equal(worldOpen(g,1),false);assert.throws(()=>applyAction(g,{type:'review',missionId:'m1',proofId:'proof-m1',approved:true,feedback:'Trying to get duplicate rewards.'}),/already/);});
test('rejection returns to proof, preserving the built asset',()=>{let g=stage(freshGame(),missions[0]);g=applyAction(g,{type:'submit',missionId:'m1',proofId:'p1',proof});g=applyAction(g,{type:'review',missionId:'m1',proofId:'p1',approved:false,feedback:'Please explain your actual participant feedback.'});assert.equal(g.missions.m1.step,4);assert.equal(g.xp,0);assert.ok(g.missions.m1.draft.length>60);g=applyAction(g,{type:'submit',missionId:'m1',proofId:'p2',proof});assert.throws(()=>applyAction(g,{type:'review',missionId:'m1',proofId:'p1',approved:true,feedback:'Old proof should not be accepted.'}));});
test('boss is proof gated and failed rounds do not grant rewards',()=>{assert.throws(()=>applyAction(freshGame(),{type:'boss',worldId:'foundation',expectedRound:0,answer:'A'.repeat(100),passed:true,feedback:'valid feedback'}),/Verify both/);let g=complete(complete(freshGame(),missions[0]),missions[1]);assert.ok(bossReady(g,0));const xp=g.xp;g=applyAction(g,{type:'boss',worldId:'foundation',expectedRound:0,answer:'A'.repeat(100),passed:false,feedback:'Needs improvement.'});assert.equal(g.xp,xp);assert.equal(g.bosses.foundation.round,0);assert.equal(worldOpen(g,1),false);});
test('all 18 missions and nine bosses can be completed without LWA or payment',()=>{let g=freshGame();for(const w of worlds){assert.ok(worldOpen(g,w.index));for(const m of missions.filter(x=>x.world===w.index))g=complete(g,m);for(let round=0;round<3;round++)g=applyAction(g,{type:'boss',worldId:w.id,expectedRound:round,answer:'Understanding: a specific real problem is described in detail.\nAction: a small respectful experiment is planned for this week.\nCheck: I will record the response and review the evidence on Friday.',passed:true,feedback:'Each rubric criterion has been demonstrated.'});assert.ok(g.bosses[w.id].won);}assert.equal(g.options.length,9);assert.equal(Object.keys(g.missions).length,18);assert.ok(guideLevel(g,'creator')>1);assert.equal(new Set(g.options).size,9);assert.throws(()=>applyAction(g,{type:'boss',worldId:'foundation',expectedRound:3,answer:'A'.repeat(100),passed:true,feedback:'Duplicate.'}),/already defeated/);});
test('training boss rejects filler in one line and adapts round requirements',()=>{const g=freshGame();assert.equal(trainingBoss(g,worlds[0],'A'.repeat(160)).passed,false);assert.equal(trainingBoss(g,worlds[0],'Understanding the current problem.\nTaking a respectful small next action.\nChecking the actual result with evidence.').passed,true);});
test('actions do not mutate the original save',()=>{const original=freshGame(),next=applyAction(original,{type:'step',missionId:'m1',expectedStep:0});assert.equal(Object.keys(original.missions).length,0);assert.equal(next.missions.m1.step,1);});
