import {before,after,test} from 'node:test';
import {readFileSync} from 'node:fs';
import {initializeTestEnvironment,assertFails,assertSucceeds} from '@firebase/rules-unit-testing';
import {doc,getDoc,setDoc} from 'firebase/firestore';
import {ref,uploadBytes,getBytes} from 'firebase/storage';
let env;
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-oyo-unlocked',firestore:{rules:readFileSync('firestore.rules','utf8')},storage:{rules:readFileSync('storage.rules','utf8')}});await env.withSecurityRulesDisabled(async c=>{await setDoc(doc(c.firestore(),'privateConfig/owner'),{uid:'owner'});await setDoc(doc(c.firestore(),'players/alice'),{game:{xp:0}});await setDoc(doc(c.firestore(),'players/alice/proofs/p1'),{status:'pending'});});});
after(async()=>env?.cleanup());
test('only the owner can read a player, and client cannot edit XP',async()=>{const a=env.authenticatedContext('alice').firestore(),b=env.authenticatedContext('bob').firestore();await assertSucceeds(getDoc(doc(a,'players/alice')));await assertFails(getDoc(doc(b,'players/alice')));await assertFails(setDoc(doc(a,'players/alice'),{game:{xp:999999}}));});
test('players and reviewers cannot directly approve proof or change entitlement',async()=>{for(const c of [env.authenticatedContext('alice'),env.authenticatedContext('owner',{owner:true})]){await assertFails(setDoc(doc(c.firestore(),'players/alice/proofs/p1'),{status:'verified'}));await assertFails(setDoc(doc(c.firestore(),'entitlements/alice'),{active:true}));}});
test('anonymous and cross-player proof reads are denied',async()=>{await assertFails(getDoc(doc(env.unauthenticatedContext().firestore(),'players/alice/proofs/p1')));await assertFails(getDoc(doc(env.authenticatedContext('bob').firestore(),'players/alice/proofs/p1')));await assertSucceeds(getDoc(doc(env.authenticatedContext('owner',{owner:true}).firestore(),'players/alice/proofs/p1')));});
test('evidence is owner-only create and cannot be overwritten',async()=>{const a=env.authenticatedContext('alice').storage(),b=env.authenticatedContext('bob').storage();await assertFails(uploadBytes(ref(b,'proofs/alice/p2/evidence'),new Uint8Array([1]),{contentType:'image/png'}));await assertSucceeds(uploadBytes(ref(a,'proofs/alice/p2/evidence'),new Uint8Array([1]),{contentType:'image/png'}));await assertFails(uploadBytes(ref(a,'proofs/alice/p2/evidence'),new Uint8Array([2]),{contentType:'image/png'}));await assertFails(uploadBytes(ref(a,'proofs/alice/p3/evidence'),new Uint8Array([1]),{contentType:'text/html'}));await assertFails(uploadBytes(ref(a,'proofs/alice/p4/evidence'),new Uint8Array(5*1024*1024+1),{contentType:'image/png'}));await assertFails(getBytes(ref(b,'proofs/alice/p2/evidence')));});

test('gamer chat is signed-in readable but server-write-only',async()=>{await env.withSecurityRulesDisabled(async c=>{await setDoc(doc(c.firestore(),'gamerChat/message1'),{text:'Hello',createdAt:1});});await assertSucceeds(getDoc(doc(env.authenticatedContext('alice').firestore(),'gamerChat/message1')));await assertFails(getDoc(doc(env.unauthenticatedContext().firestore(),'gamerChat/message1')));await assertFails(setDoc(doc(env.authenticatedContext('alice').firestore(),'gamerChat/message2'),{text:'Forged',uid:'bob'}));await assertFails(setDoc(doc(env.authenticatedContext('alice').firestore(),'appConfig/resources'),{mainUrl:'https://example.com',products:[]}));});

test('legacy roles and an owner claim on another UID cannot read other player proofs',async()=>{await assertFails(getDoc(doc(env.authenticatedContext('bob',{owner:true}).firestore(),'players/alice/proofs/p1')));await assertFails(getDoc(doc(env.authenticatedContext('legacy',{reviewer:true}).firestore(),'players/alice/proofs/p1')));await assertFails(getDoc(doc(env.authenticatedContext('alice').firestore(),'privateConfig/owner')));await assertFails(setDoc(doc(env.authenticatedContext('alice').firestore(),'privateConfig/owner'),{uid:'alice'}));});
