import {freshGame,applyAction,checkProof,safeText,guideLevel} from '../functions/game/engine.js';
import {missions,worlds,guides} from '../functions/game/content.js';
const open=()=>new Promise((resolve,reject)=>{const r=indexedDB.open('oyo-device-adventure',1);r.onupgradeneeded=()=>r.result.createObjectStore('save');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
async function transaction(mode,fn){const db=await open();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('save',mode);let result;fn(tx.objectStore('save'),v=>result=v);tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Device storage unavailable.'));});}finally{db.close();}}
export const read=async()=>await transaction('readonly',(s,done)=>{const r=s.get('adventure');r.onsuccess=()=>done(r.result);})||{game:freshGame(),proofs:[]};
export const write=value=>transaction('readwrite',s=>s.put({game:value.game,proofs:value.proofs},'adventure'));
export const clear=()=>transaction('readwrite',s=>s.clear());
export const file=id=>transaction('readonly',(s,done)=>{const r=s.get('file-'+id);r.onsuccess=()=>done(r.result);});
export const action=(s,a)=>{if(!['profile','step'].includes(a.type))throw Error('Unsupported device action.');return {game:applyAction(s.game,a),proofs:s.proofs};};
export async function submit(s,missionId,proof,attachment){checkProof(proof,missions.find(m=>m.id===missionId));if(attachment&&(attachment.size>5242880||!['image/jpeg','image/png','image/webp','application/pdf'].includes(attachment.type)))throw Error('Choose an image or PDF under 5 MB.');const id=crypto.randomUUID(),game=applyAction(s.game,{type:'submit',missionId,proofId:id,proof});if(attachment)await transaction('readwrite',store=>store.put(attachment,'file-'+id));return {game,proofs:[...s.proofs,{...proof,id,missionId,status:'pending',createdAt:Date.now(),hasFile:!!attachment,fileName:attachment?.name||'',provenance:'device'}]};}
export function review(s,id){const p=s.proofs.find(p=>p.id===id);if(!p)throw Error('Proof not found.');const feedback='Self-reviewed on this device. You attested that the real-world action and all evidence criteria are complete. This is not owner-verified evidence.';return {game:applyAction(s.game,{type:'review',missionId:p.missionId,proofId:id,approved:true,feedback}),proofs:s.proofs.map(x=>x.id===id?{...x,status:'verified',provenance:'device',feedback}:x)};}
const playbooks={
strategist:'Choose one reachable audience and one costly problem. Interview three people about the last time it happened, what they tried, and what they paid in time or money. Record their exact language. Offer one small test only after evidence repeats. Decide in advance what response would make you change direction.',
creator:'Write a message with a specific audience, a recognizable problem, one useful insight, a concrete example, and a low-pressure invitation. Example: “Still rewriting your client onboarding emails? Here are three questions to collect before you begin. Want the checklist?” Test two hooks with the same audience; compare qualified replies, not just likes.',
builder:'Define the deliverable, who it helps, exclusions, timeline, inputs needed from the customer, and price. Start with a small paid pilot if appropriate. Test the full delivery workflow yourself. Measure time spent and customer feedback before expanding scope. Never imply a result you cannot substantiate.',
closer:'Start with discovery: “What prompted you to look at this now? How do you handle it today? What would a useful improvement look like? Who else is involved?” Summarize their need before recommending an offer. Ask permission: “Would you like to see how this scope could address that?” Close on a clear, mutual next step with an agreed date. Respect a no.',
analyst:'Locate the bottleneck: reach → qualified conversations → offers → purchases → successful delivery. Count each stage for a fixed period, including the denominator. Change one factor at a time. Low reply rate suggests message or audience fit; low close rate may be fit, offer clarity, trust, or timing. Interview lost prospects before deciding.',
spark:'Name the exact action you are avoiding. Shrink it to a ten-minute draft or one respectful conversation. Write an if-then plan: “After lunch, I will draft one invitation.” Record the attempt and what you learned; do not judge the experiment only by a sale. Ask for support if the next step exceeds your capacity.'};
export function guide(s,id,message){safeText(message,3,2000);if(!guides.some(g=>g.id===id))throw Error('Unknown guide.');let extra='';if(/price|expensive|budget|cost/i.test(message))extra='\nPrice objection: “When you say expensive, is it outside your available budget, or are you unsure the scope is worth it?” If budget is the issue, discuss a genuinely smaller scope or pause. If value is unclear, connect deliverables to their stated need with relevant evidence; never promise returns.';else if(/trust|proof|scam/i.test(message))extra='\nTrust objection: Ask what evidence would help. Show a relevant sample, clear scope, and accurate limitations. Do not invent testimonials. Give the person space to decide.';else if(/time|later|think/i.test(message))extra='\nTiming objection: “What would need to change for this to become a priority?” Agree on a follow-up only with permission. Do not invent scarcity.';const lvl=guideLevel(s.game,id);const text=`Offline strategy library · ${guides.find(g=>g.id===id).name} · Level ${lvl}\n${playbooks[id]}${extra}\n${lvl>=6?'Advanced task: state two alternative explanations for your results and design a small experiment to distinguish them.':lvl>=3?'Next task: compare two approaches and write the evidence that would change your choice.':'Next task: apply this framework to one real person or draft today.'}\nThese are curated frameworks selected by topic, not a live AI analysis of your message. Open your online account for adaptive coaching.`;const game=structuredClone(s.game);game.chats[id]=[...(game.chats[id]||[]),{role:'user',text:message},{role:'assistant',text}].slice(-30);return {text,save:{game,proofs:s.proofs}};}
export const offlineRounds=[
{objection:'“This costs more than I expected.”',options:['Promise they will earn it back.','Ask whether the concern is available budget or confidence in the scope’s value.','Offer an immediate discount before asking questions.'],correct:1,feedback:'Clarify the concern before proposing a solution. Budget and value uncertainty need different responses.'},
{objection:'“I need to ask my partner, and I have very little time.”',options:['Respect the decision process; offer a concise scope and an optional joint conversation.','Say a serious buyer would decide now.','Skip the partner and take payment.'],correct:0,feedback:'Respect authority and time constraints. Make an informed decision easier without bypassing another decision-maker.'},
{objection:'“Your first suggestion didn’t solve my concern. I’m not convinced.”',options:['Repeat the pitch more confidently.','Guarantee success if they buy today.','Ask what remains unresolved, offer relevant evidence or a smaller suitable scope, and accept no fit.'],correct:2,feedback:'Acknowledge the failed approach. Investigate the unresolved issue, adjust honestly, and respect a clear no.'}
];
export function battle(s,worldId,answer,choice){const w=worlds.find(w=>w.id===worldId);if(!w)throw Error('Unknown world.');const round=s.game.bosses[worldId]?.round||0;const scenario=offlineRounds[Math.min(round,2)];if(!Number.isInteger(choice)||choice<0||choice>2)throw Error('Choose a response strategy.');safeText(answer,40,3000);const passed=choice===scenario.correct;const feedback=`${passed?'Strategy selected correctly.':'Reconsider your strategy.'} ${scenario.feedback} Your written application is saved for your own reflection; it has not been assessed by AI.`;return {passed,feedback,save:{game:applyAction(s.game,{type:'boss',worldId,answer,expectedRound:round,passed,feedback}),proofs:s.proofs}};}
export function restore(v){if(v.mode!=='device'||v.game?.version!==1||!Array.isArray(v.proofs)||!v.game.profile||!v.game.missions||!v.game.bosses||!Array.isArray(v.game.options)||!Array.isArray(v.game.achievements)||!v.game.chats||!v.game.guideXp||!v.game.skills||!Number.isFinite(v.game.xp))throw Error('Choose an OYO device backup. Online progress cannot be imported.');return {game:v.game,proofs:v.proofs.map(p=>({...p,hasFile:false,attachment:null,provenance:'device'}))};}
